### ISSUE TITLE
gdal-config --version gives GDAL version that is missing on pypi

### ISSUE THREAD

**Issue by decentral1se** [tehamalab/gdal2tiles#8]
* gdal2tiles version: latest pypi
* GDAL version: 2.1.2
* Python version: py3
* Operating System: debian stretch

### Description

gdal-config seems to be giving a bad pypi gdal version?

### What I Did

```
$ apt install -y libgdal-dev
$ pip install gdal2tiles
```

And then I see:

> (.venv) ➜  ~ (master) ✗ pip install gdal2tiles
> Collecting gdal2tiles         
>   Using cached https://files.pythonhosted.org/packages/1e/5d/d75fd3c1a6e748c93af9cc5bab21c26d783cadc8073a4621bde10fe49b45/gdal2tiles-0.1.5.tar.gz
> ERROR: Could not find a version that satisfies the requirement GDAL==2.1.2 (from gdal2tiles) (from versions: 1.5.0, 1.5.2, 1.6.0, 1.6.1, 1.7.0, 1.7.1, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.11.0, 1.11.1, 1.11.2, 2.0.0, 2.0.1, 2.1.0, 2.1.3, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.4.0, 2.4.2, 2.4.3, 3.0.0, 3.0.1, 3.0.2)
> ERROR: No matching distribution found for GDAL==2.1.2 (from gdal2tiles)

So, gdal-config --version gives back 2.1.2 and that doesn't seem to exist on the pypi release log over at https://pypi.org/project/GDAL/#history. I can hotfix to get an install working but it seems like the assumption that gdal-config gives a working version for install leads to this issue.

**Comment by machakux** [comment]
I think this is fixed now since version 0.1.6 uses ``pygdal`` (https://github.com/nextgis/pygdal) instead of GDAL. Pygdal provides more convenient installation of GDAL.

**Comment by decentral1se** [comment]
Works! Thanks :+1:
